### ISSUE TITLE
can't install see log bellow not sure if this is your prob or panda's 

### ISSUE THREAD

**Issue by grizzlysmit** [avuserow/perl6-datetime-format-likego#2]
It always try's to find the stuff relative to where I run panda 

<pre>
panda  install DateTime::Format::LikeGo
==> Fetching DateTime::Format::LikeGo
==> Building DateTime::Format::LikeGo
==> Testing DateTime::Format::LikeGo
t/basic.t .. ok
All tests successful.
Files=1, Tests=3, 13 wallclock secs ( 0.05 usr  0.01 sys +  7.22 cusr  0.53 csys =  7.81 CPU)
Result: PASS
==> Installing DateTime::Format::LikeGo
Failed to copy '/home/grizzlysmit/.panda-work/1451268783_1/lib/DateTime/Format/LikeGo.pm' to '/home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/07AD8FE6319510008C5257C2CB81DC9B14963B10': Failed to copy file: no such file or directory
  in any  at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm line 1
  in block  at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/29F09C757412FD487CB148BC6EE267492959C486 line 61
  in sub indir at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/9B69159C1933BD092F0241E12217286E7A0B5A20 line 20
  in method install at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/29F09C757412FD487CB148BC6EE267492959C486 line 42
  in method install at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/090543F8DBD29804D76BAAC0103FF6D337DED39C line 146
  in method resolve at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/090543F8DBD29804D76BAAC0103FF6D337DED39C line 219
  in sub MAIN at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/resources/6CE0986C872389704E6837E8E18FB8B60EA087C1 line 18
  in block <unit> at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/resources/6CE0986C872389704E6837E8E18FB8B60EA087C1 line 150

Actually thrown at:
  in any  at gen/moar/m-Metamodel.nqp line 3041
  in block  at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/29F09C757412FD487CB148BC6EE267492959C486 line 61
  in sub indir at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/9B69159C1933BD092F0241E12217286E7A0B5A20 line 20
  in method install at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/29F09C757412FD487CB148BC6EE267492959C486 line 42
  in method install at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/090543F8DBD29804D76BAAC0103FF6D337DED39C line 146
  in method resolve at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/090543F8DBD29804D76BAAC0103FF6D337DED39C line 219
  in sub MAIN at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/resources/6CE0986C872389704E6837E8E18FB8B60EA087C1 line 18
  in block <unit> at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/resources/6CE0986C872389704E6837E8E18FB8B60EA087C1 line 150
</pre>

**Comment by avuserow** [comment]
Typo in META.info. Fixed, thanks!
